services:
  - type: web
    name: eshopping-api
    env: node
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: CLIENT_URL_USER
        value: https://your-user-frontend.vercel.app
      - key: CLIENT_URL_ADMIN
        value: https://your-admin-frontend.vercel.app