# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
name: Node.js CI

on:
  push:
    branches: [ "dev", "gooddev" ]
  pull_request:
    branches: [ "dev", "gooddev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            client/user/package-lock.json
            client/admin/package-lock.json

      # Server
      - name: Install server deps
        run: npm ci
        working-directory: ./server
      - name: Typecheck server
        run: node --check app.js
        working-directory: ./server

      # Client user
      - name: Install user client deps
        run: npm ci
        working-directory: ./client/user
      - name: Build user client
        run: npm run build
        working-directory: ./client/user

      # Client admin
      - name: Install admin client deps
        run: npm ci
        working-directory: ./client/admin
      - name: Build admin client
        run: npm run build
        working-directory: ./client/admin